meta:
  name: flufik
  version: 1.5
  release: 2.ubuntu
  arch: x86_64
  maintainer: Eduard Gevorkyan
  summary: |-
    Flufik DEB Package
  description: |-
    Flufik package which can be deployed on DEB based Linux OS
files:
  generic:
    - destination: /bin/flufik
      source: ./bin/linux/amd64/flufik
      owner: root
      group: root
      mode: 0755
