---

env:
  CGO_ENABLED: 0
  VERSION: 1.5
  RELEASE: 2

  REPO_NAME: eduard1001171985
  IMG_NAME: flufik
  IMG_DEV_NAME: flufikdev
  FLUFIK_PACKAGE: flufik
  QUAY_REPO_NAME: quay.io/rhlcloud/flufik


functions:
  - name: building
    description: Build with archieve
    run:
      - $(prepare-env)
      - $(build-linux)
      #- $(build-mac)
      - $(build-pkg)
      #- $(zip)
      #- $(tar)
      #- mv flufik-bins/darwin/flufik /usr/local/bin/flufik
      - rm -rf flufik-bins
      - rm -rf temp
      - rm -rf .env

  - name: dirs
    description: make dirs
    run:
      - mkdir -p packs

  - name: build-linux-amd64
    description: build stats tool for Linux
    env:
      GOOS: linux
      GOARCH: amd64
    run:
      - go build -ldflags="-X 'github.com/egevorkyan/flufik/core.Version=${VERSION}-${RELEASE}'" -o bin/linux/amd64/flufik cmd/main/main.go

  - name: build-linux-arm64
    description: build stats tool for Linux
    env:
      GOOS: linux
      GOARCH: arm64
    run:
      - mkdir -p linux/
      - go build -ldflags="-X 'github.com/egevorkyan/flufik/core.Version=${VERSION}-${RELEASE}'" -o bin/linux/arm64/flufik cmd/main/main.go

  - name: build-darwin-amd64
    description: build flufik tool for MacOS
    env:
      GOOS: darwin
      GOARCH: amd64
    run:
      - go build -ldflags="-X 'github.com/egevorkyan/flufik/core.Version=${VERSION}-${RELEASE}'" -o bin/darwin/amd64/flufik cmd/main/main.go

  - name: build-darwin-arm64
    description: build flufik tool for MacOS
    env:
      GOOS: darwin
      GOARCH: arm64
    run:
      - go build -ldflags="-X 'github.com/egevorkyan/flufik/core.Version=${VERSION}-${RELEASE}'" -o bin/darwin/arm64/flufik cmd/main/main.go

  - name: build-packs
    description: building final packages
    run:
      - flufik build -c flufik-pack-config/config-amd64-rhel8-rpm.yaml -p rpm -d packs/
      - flufik push generic -u admin -p ${FPWD} --yum -f repo.apps.arencloud.com -d rhel --os-version 8 -a amd64 -b packs/flufik-${VERSION}-${RELEASE}.el8.x86_64.rpm
      - flufik build -c flufik-pack-config/config-arm64-rhel8-rpm.yaml -p rpm -d packs/
      - flufik push generic -u admin -p ${FPWD} --yum -f repo.apps.arencloud.com -d rhel --os-version 8 -a arm64 -b packs/flufik-${VERSION}-${RELEASE}.el8.aarch64.rpm
      - flufik build -c flufik-pack-config/config-amd64-rhel9-rpm.yaml -p rpm -d packs/
      - flufik push generic -u admin -p ${FPWD} --yum -f repo.apps.arencloud.com -d rhel --os-version 9 -a amd64 -b packs/flufik-${VERSION}-${RELEASE}.el9.x86_64.rpm
      - flufik build -c flufik-pack-config/config-arm64-rhel9-rpm.yaml -p rpm -d packs/
      - flufik push generic -u admin -p ${FPWD} --yum -f repo.apps.arencloud.com -d rhel --os-version 9 -a arm64 -b packs/flufik-${VERSION}-${RELEASE}.el9.aarch64.rpm
      - flufik build -c flufik-pack-config/config-amd64-fedora-rpm.yaml -p rpm -d packs/
      - flufik push generic -u admin -p ${FPWD} --yum -f repo.apps.arencloud.com -d fedora --os-version 35 -a amd64 -b packs/flufik-${VERSION}-${RELEASE}.fedora.x86_64.rpm
      - flufik build -c flufik-pack-config/config-arm64-fedora-rpm.yaml -p rpm -d packs/
      - flufik push generic -u admin -p ${FPWD} --yum -f repo.apps.arencloud.com -d fedora --os-version 35 -a arm64 -b packs/flufik-${VERSION}-${RELEASE}.fedora.aarch64.rpm
      - flufik build -c flufik-pack-config/config-amd64-deb.yaml -p deb -d packs/
      - flufik push generic -u admin -p ${FPWD} --apt -f repo.apps.arencloud.com -d focal -a amd64 -s main -b packs/flufik_${VERSION}-${RELEASE}.ubuntu_amd64.deb
      - flufik push generic -u admin -p ${FPWD} --apt -f repo.apps.arencloud.com -d jammy -a amd64 -s main -b packs/flufik_${VERSION}-${RELEASE}.ubuntu_amd64.deb
      - flufik build -c flufik-pack-config/config-arm64-deb.yaml -p deb -d packs/
      - flufik push generic -u admin -p ${FPWD} --apt -f repo.apps.arencloud.com -d focal -a arm64 -s main -b packs/flufik_${VERSION}-${RELEASE}.ubuntu_arm64.deb
      - flufik push generic -u admin -p ${FPWD} --apt -f repo.apps.arencloud.com -d jammy -a arm64 -s main -b packs/flufik_${VERSION}-${RELEASE}.ubuntu_arm64.deb
      - rm -rf bin
      - rm -rf packs

  - name: build-final
    description: package build
    run:
      - $(dirs)
      - $(build-linux-amd64)
      - $(build-linux-arm64)
      - $(build-darwin-amd64)
      - $(build-darwin-arm64)
      - $(build-packs)


  - name: zip
    description: archiving flufik binaries
    run:
      - zip -r ${HOME}/.flufik/output/flufik-${VERSION}-${RELEASE}.zip flufik-bins

  - name: tar
    description: archiving flufik binaries
    run:
      - tar czvf ${HOME}/.flufik/output/flufik-${VERSION}-${RELEASE}.tar.gz flufik-bins

  - name: prepare-env
    description: environment preparation
    run:
      - rm -rf temp
      - mkdir temp
      - cp ${HOME}/.flufik/configs/config-rpm.yaml.tem temp/
      - cp ${HOME}/.flufik/configs/config-deb.yaml.tem temp/
      - cp ${HOME}/.flufik/configs/.env .
      - art merge temp/config-rpm.yaml.tem
      - art merge temp/config-deb.yaml.tem

  - name: build-pkg
    description: build rpm and deb packages
    run:
      - flufik build -c temp/config-rpm.yaml -p rpm
      - flufik build -c temp/config-deb.yaml -p deb
      #- flufik push -d ${RELEASE_RPM} -b flufik-${MAJORVERSION}-${VERSION}.${RELEASE_RPM}.${ARCH}.rpm -p ${JFROG_REPO_PWD} -m temp -w ${JFROG_REPO} -l ${JFROG_REPO_RPM} -u ${JFROG_REPO_USER}
      #- flufik push -a ${ARCH_DEB} -d ${DIST} -b flufik_${MAJORVERSION}-${VERSION}_${ARCH_DEB}.deb -p ${JFROG_REPO_PWD} -m temp -w ${JFROG_REPO} -l ${JFROG_REPO_DEB} -u ${JFROG_REPO_USER}

  - name: build-image
    description: builds and push docker image
    run:
      #- art run $(build-linux) ${ARTISAN_REF}
      - docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --push -t ${REPO_NAME}/${IMG_NAME}:${VERSION}.${RELEASE} -t ${REPO_NAME}/${IMG_NAME}:latest .
      - docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --push -t ${QUAY_REPO_NAME}:${VERSION}.${RELEASE} -t ${QUAY_REPO_NAME}:latest .
      #- docker tag ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} ${REPO_NAME}/${IMG_NAME}:latest
        #- docker push ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF}
        #- docker push ${REPO_NAME}/${IMG_NAME}:latest
      #- rm Docker/flufik

  - name: build-dev
    description: builds and push dev docker image
    run:
      #- art run $(build-linux)
      - docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --push -t ${REPO_NAME}/${IMG_DEV_NAME}:${ARTISAN_REF} -t ${REPO_NAME}/${IMG_DEV_NAME}:latest .
      #- docker buildx build --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x --push -t ${QUAY_REPO_NAME}:${ARTISAN_REF} -t ${QUAY_REPO_NAME}:latest .
        #- docker tag ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} ${REPO_NAME}/${IMG_NAME}:latest
      #- docker push ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF}
      #- docker push ${REPO_NAME}/${IMG_NAME}:latest
      #- rm Docker/flufik