---

env:
  CGO_ENABLED: 0
  GOARCH: amd64
  VERSION: 0.3.0
  RELEASE: 1

  REPO_NAME: eduard1001171985
  IMG_NAME: flufik
  FLUFIK_PACKAGE: flufik


functions:
  - name: building
    description: Build with archieve
    run:
      - $(prepare-env)
      - $(build-linux)
      #- $(build-mac)
      - $(build-pkg)
      #- $(zip)
      #- $(tar)
      #- mv flufik-bins/darwin/flufik /usr/local/bin/flufik
      - rm -rf flufik-bins
      - rm -rf temp
      - rm -rf .env

  - name: build-linux
    description: build stats tool for Linux
    env:
      GOOS: linux
    run:
      - go build -ldflags="-X 'github.com/egevorkyan/flufik/core.Version=${VERSION}-${RELEASE}'" -o Docker/flufik cmd/main/main.go
  - name: build-mac
    description: build flufik tool for MacOS
    env:
      GOOS: darwin
    run:
      - go build -ldflags="-X 'github.com/egevorkyan/flufik/core.Version=${VERSION}-${RELEASE}'" -o flufik-bins/darwin/flufik cmd/main/main.go

  - name: zip
    description: archiving flufik binaries
    run:
      - zip -r ${HOME}/.flufik/output/flufik-${VERSION}-${RELEASE}.zip flufik-bins

  - name: tar
    description: archiving flufik binaries
    run:
      - tar czvf ${HOME}/.flufik/output/flufik-${VERSION}-${RELEASE}.tar.gz flufik-bins

  - name: prepare-env
    description: environment preparation
    run:
      - rm -rf temp
      - mkdir temp
      - cp ${HOME}/.flufik/configs/config-rpm.yaml.tem temp/
      - cp ${HOME}/.flufik/configs/config-deb.yaml.tem temp/
      - cp ${HOME}/.flufik/configs/.env .
      - art merge temp/config-rpm.yaml.tem
      - art merge temp/config-deb.yaml.tem

  - name: build-pkg
    description: build rpm and deb packages
    run:
      - flufik build -c temp/config-rpm.yaml -p rpm
      - flufik build -c temp/config-deb.yaml -p deb
      #- flufik push -d ${RELEASE_RPM} -b flufik-${MAJORVERSION}-${VERSION}.${RELEASE_RPM}.${ARCH}.rpm -p ${JFROG_REPO_PWD} -m temp -w ${JFROG_REPO} -l ${JFROG_REPO_RPM} -u ${JFROG_REPO_USER}
      #- flufik push -a ${ARCH_DEB} -d ${DIST} -b flufik_${MAJORVERSION}-${VERSION}_${ARCH_DEB}.deb -p ${JFROG_REPO_PWD} -m temp -w ${JFROG_REPO} -l ${JFROG_REPO_DEB} -u ${JFROG_REPO_USER}

  - name: build-image
    description: builds and push docker image
    run:
      - art run $(build-linux)
      - docker build -f Docker/Dockerfile -t ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} .
      - docker tag ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF} ${REPO_NAME}/${IMG_NAME}:latest
        #- docker push ${REPO_NAME}/${IMG_NAME}:${ARTISAN_REF}
        #- docker push ${REPO_NAME}/${IMG_NAME}:latest
      - rm Docker/flufik