version: "3.8"
services:
  flufik:
    image: eduard1001171985/flufik:latest
    container_name: flufik
    ports:
      - "80:8080"
    environment:
      - FLUFIK_DEBUG=0
      - FLUFIK_PUBLIC_URL=localhost
      - FLUFIK_SUPPORT_ARCH=all i386 amd64
      - FLUFIK_SECTIONS=main
      - FLUFIK_DISTRO_NAMES=stable
      - FLUFIK_RPM_REPO_NAME=redhat
    networks:
      - flufik
    volumes:
      - flufik:/opt/flufik
volumes:
  flufik:

networks:
  flufik:
    driver: bridge