name: Flufik autoreleasing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        run: |
          echo "Done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
  release-matrix:
    name: Release flufik
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, darwin/amd64, darwin/arm64
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64, arm64 ]
        exclude:
          - goarch: "386"
            goos: linux
          - goarch: "386"
            goos: windows
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date) >> ${GITHUB_ENV}
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.17
          ldflags: -X "core.Version=${{ env.APP_VERSION }}-${{ env.BUILD_TIME }}"
          project_path: "./cmd/main"
          binary_name: "flufik"
          executable_compression: upx
          overwrite: TRUE
          sha256sum: TRUE
          release_tag: latest